pull_request_rules:
  - name: automatically update PRs
    conditions:
      - or:
          - author=scalatsi
          - author=scala-steward
          - author=dhoepelman
    actions:
      update:
  - name: automatically merge scala-steward PRs
    conditions:
      - or:
          - author=scalatsi
          - author=scala-steward
      - body~=labels:.*semver-((minor)|(patch)).*
    actions:
      merge:
        method: squash
